# Generated by Django 4.2.4 on 2023-08-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
    ]
